address: "0.0.0.0:8010"
socketAddress: "0.0.0.0:8011"
expired: 24
secretkey: "qhcloud"
middlewares:
  - jwt2
namespaces:
k8s:
  kubeconfig: /Users/mojo/.kube/config # 在本地DEBUG用,配置本地kubeconfig地址，不配置便加载inclusterconfig
  prometheus:
repository: # 正式环境使用harbor作为应用仓库
  name: bitnami
  url: https://registry.bngrp.cn/chartrepo
  username: qhwk
  password: Bnbn2020
  maxHistory: 20 # the max history of helm release to list
  storageBackend: # default to use secrets to storage release
  type: ordinary  # ordinary(e.g. bitnami)、harbor
auth:
  url: http://10.60.41.127:35357/v3
runMode: dev