name: chart
replicas: 1 # the default for all services
imagePullSecrets:
- name: secretDemo
services:
- demo:
    type: deployments # kubernetes resource type
    expose: # service define
      clusterIP: None
      type: ClusterIP
      ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: tcp-80
    annotations:
      kk: vv
      k: v
    replicas: 2
    imagePullPolicy: Always
    podAnnotations:
      pkk: pvv
    hostIPC: false
    volumes:
    - name: test
      hostPath:
        path: /etc/bbb
    imagePullSecrets:
    - name: default
    containers:
    - name: demo
      image: nginx
      resources:
        limits:
          cpu: 0.3
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 80Mi