apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-demo
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if (index .Values.services 0).demo.imagePullSecrets }}
      imagePullSecrets:
      {{- range (index .Values.services 0).demo.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (index .Values.services 0).demo.hostIPC }}
      hostIPC: {{ (index .Values.services 0).demo.hostIPC }}
      {{- end }}
      {{- if (index .Values.services 0).demo.volumes }}
      volumes: {{- (index .Values.services 0).demo.volumes | toYaml | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
